TARGET = cody_launcher
BUILD_DIR ?= build-cody
INTFLASH_BANK ?= 2

# Bank 2 launcher build. This intentionally reuses the hardware
# initialization and support code from the bootloader project, but replaces
# Core/Src/bootloader.c with Core/Src/cody_launcher.c.
C_SOURCES =  \
Core/Src/gw_sdcard.c \
Core/Src/gw_timer.c \
Core/Src/gw_buttons.c \
Core/Src/gw_flash.c \
Core/Src/gw_gui.c \
Core/Src/gw_lcd.c \
Core/Src/porting/gw_alloc.c \
Core/Src/main.c \
Core/Src/cody_launcher.c \
Core/Src/syscalls.c \
Core/Src/bq24072.c \
Core/Src/stm32h7xx_hal_msp.c \
Core/Src/stm32h7xx_it.c \
Core/Src/system_stm32h7xx.c \
Core/src/softspi.c

FATFS_C_SOURCES = \
Core/Src/porting/lib/FatFs/user_diskio.c \
Core/Src/porting/lib/FatFs/ff.c \
Core/Src/porting/lib/FatFs/ffsystem.c \
Core/Src/porting/lib/FatFs/ffunicode.c \
Core/Src/porting/lib/FatFs/sd_crc.c \
Core/Src/porting/lib/FatFs/user_diskio_spi.c \
Core/Src/porting/lib/FatFs/user_diskio_softspi.c

C_INCLUDES +=  \
-ICore/Inc \
-ICore/Src/porting/lib \
-ICore/Src/porting/lib/FatFs \
-Iretro-go-stm32/components/odroid \
-I./

FATFS_C_INCLUDES += \
-ICore/Src/porting/lib/FatFs

include Makefile.common

$(BUILD_DIR)/$(TARGET).bin: $(BUILD_DIR)/$(TARGET).elf | $(BUILD_DIR)
	$(V)$(ECHO) [ BIN ] $(notdir $@)
	$(V)$(BIN) -j .isr_vector -j .text -j .rodata -j .ARM.extab -j .preinit_array -j .init_array -j .fini_array -j .data $< $(BUILD_DIR)/$(TARGET).bin
